/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/gogo/protobuf/gogoproto/gogo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "github.com/gogo/protobuf/gogoproto/gogo.pb-c.h"
