/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/TheThingsNetwork/ttn/api/api.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "github.com/TheThingsNetwork/ttn/api/api.pb-c.h"
void   api__ack__init
                     (Api__Ack         *message)
{
  static Api__Ack init_value = API__ACK__INIT;
  *message = init_value;
}
size_t api__ack__get_packed_size
                     (const Api__Ack *message)
{
  assert(message->base.descriptor == &api__ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t api__ack__pack
                     (const Api__Ack *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &api__ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t api__ack__pack_to_buffer
                     (const Api__Ack *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &api__ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Api__Ack *
       api__ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Api__Ack *)
     protobuf_c_message_unpack (&api__ack__descriptor,
                                allocator, len, data);
}
void   api__ack__free_unpacked
                     (Api__Ack *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &api__ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   api__percentiles__init
                     (Api__Percentiles         *message)
{
  static Api__Percentiles init_value = API__PERCENTILES__INIT;
  *message = init_value;
}
size_t api__percentiles__get_packed_size
                     (const Api__Percentiles *message)
{
  assert(message->base.descriptor == &api__percentiles__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t api__percentiles__pack
                     (const Api__Percentiles *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &api__percentiles__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t api__percentiles__pack_to_buffer
                     (const Api__Percentiles *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &api__percentiles__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Api__Percentiles *
       api__percentiles__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Api__Percentiles *)
     protobuf_c_message_unpack (&api__percentiles__descriptor,
                                allocator, len, data);
}
void   api__percentiles__free_unpacked
                     (Api__Percentiles *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &api__percentiles__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   api__rates__init
                     (Api__Rates         *message)
{
  static Api__Rates init_value = API__RATES__INIT;
  *message = init_value;
}
size_t api__rates__get_packed_size
                     (const Api__Rates *message)
{
  assert(message->base.descriptor == &api__rates__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t api__rates__pack
                     (const Api__Rates *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &api__rates__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t api__rates__pack_to_buffer
                     (const Api__Rates *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &api__rates__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Api__Rates *
       api__rates__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Api__Rates *)
     protobuf_c_message_unpack (&api__rates__descriptor,
                                allocator, len, data);
}
void   api__rates__free_unpacked
                     (Api__Rates *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &api__rates__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   api__server_metadata__init
                     (Api__ServerMetadata         *message)
{
  static Api__ServerMetadata init_value = API__SERVER_METADATA__INIT;
  *message = init_value;
}
size_t api__server_metadata__get_packed_size
                     (const Api__ServerMetadata *message)
{
  assert(message->base.descriptor == &api__server_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t api__server_metadata__pack
                     (const Api__ServerMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &api__server_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t api__server_metadata__pack_to_buffer
                     (const Api__ServerMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &api__server_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Api__ServerMetadata *
       api__server_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Api__ServerMetadata *)
     protobuf_c_message_unpack (&api__server_metadata__descriptor,
                                allocator, len, data);
}
void   api__server_metadata__free_unpacked
                     (Api__ServerMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &api__server_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define api__ack__field_descriptors NULL
#define api__ack__field_indices_by_name NULL
#define api__ack__number_ranges NULL
const ProtobufCMessageDescriptor api__ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "api.Ack",
  "Ack",
  "Api__Ack",
  "api",
  sizeof(Api__Ack),
  0,
  api__ack__field_descriptors,
  api__ack__field_indices_by_name,
  0,  api__ack__number_ranges,
  (ProtobufCMessageInit) api__ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor api__percentiles__field_descriptors[9] =
{
  {
    "percentile1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile1),
    offsetof(Api__Percentiles, percentile1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile5",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile5),
    offsetof(Api__Percentiles, percentile5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile10",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile10),
    offsetof(Api__Percentiles, percentile10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile25",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile25),
    offsetof(Api__Percentiles, percentile25),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile50",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile50),
    offsetof(Api__Percentiles, percentile50),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile75",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile75),
    offsetof(Api__Percentiles, percentile75),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile90",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile90),
    offsetof(Api__Percentiles, percentile90),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile95",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile95),
    offsetof(Api__Percentiles, percentile95),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "percentile99",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Percentiles, has_percentile99),
    offsetof(Api__Percentiles, percentile99),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned api__percentiles__field_indices_by_name[] = {
  0,   /* field[0] = percentile1 */
  2,   /* field[2] = percentile10 */
  3,   /* field[3] = percentile25 */
  1,   /* field[1] = percentile5 */
  4,   /* field[4] = percentile50 */
  5,   /* field[5] = percentile75 */
  6,   /* field[6] = percentile90 */
  7,   /* field[7] = percentile95 */
  8,   /* field[8] = percentile99 */
};
static const ProtobufCIntRange api__percentiles__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor api__percentiles__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "api.Percentiles",
  "Percentiles",
  "Api__Percentiles",
  "api",
  sizeof(Api__Percentiles),
  9,
  api__percentiles__field_descriptors,
  api__percentiles__field_indices_by_name,
  1,  api__percentiles__number_ranges,
  (ProtobufCMessageInit) api__percentiles__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor api__rates__field_descriptors[3] =
{
  {
    "rate1",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Rates, has_rate1),
    offsetof(Api__Rates, rate1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate5",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Rates, has_rate5),
    offsetof(Api__Rates, rate5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rate15",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Api__Rates, has_rate15),
    offsetof(Api__Rates, rate15),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned api__rates__field_indices_by_name[] = {
  0,   /* field[0] = rate1 */
  2,   /* field[2] = rate15 */
  1,   /* field[1] = rate5 */
};
static const ProtobufCIntRange api__rates__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor api__rates__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "api.Rates",
  "Rates",
  "Api__Rates",
  "api",
  sizeof(Api__Rates),
  3,
  api__rates__field_descriptors,
  api__rates__field_indices_by_name,
  1,  api__rates__number_ranges,
  (ProtobufCMessageInit) api__rates__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define api__server_metadata__field_descriptors NULL
#define api__server_metadata__field_indices_by_name NULL
#define api__server_metadata__number_ranges NULL
const ProtobufCMessageDescriptor api__server_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "api.ServerMetadata",
  "ServerMetadata",
  "Api__ServerMetadata",
  "api",
  sizeof(Api__ServerMetadata),
  0,
  api__server_metadata__field_descriptors,
  api__server_metadata__field_indices_by_name,
  0,  api__server_metadata__number_ranges,
  (ProtobufCMessageInit) api__server_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
