/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/TheThingsNetwork/ttn/api/router/router.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "github.com/TheThingsNetwork/ttn/api/router/router.pb-c.h"
void   router__subscribe_request__init
                     (Router__SubscribeRequest         *message)
{
  static Router__SubscribeRequest init_value = ROUTER__SUBSCRIBE_REQUEST__INIT;
  *message = init_value;
}
size_t router__subscribe_request__get_packed_size
                     (const Router__SubscribeRequest *message)
{
  assert(message->base.descriptor == &router__subscribe_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__subscribe_request__pack
                     (const Router__SubscribeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__subscribe_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__subscribe_request__pack_to_buffer
                     (const Router__SubscribeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__subscribe_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__SubscribeRequest *
       router__subscribe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__SubscribeRequest *)
     protobuf_c_message_unpack (&router__subscribe_request__descriptor,
                                allocator, len, data);
}
void   router__subscribe_request__free_unpacked
                     (Router__SubscribeRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__subscribe_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__uplink_message__init
                     (Router__UplinkMessage         *message)
{
  static Router__UplinkMessage init_value = ROUTER__UPLINK_MESSAGE__INIT;
  *message = init_value;
}
size_t router__uplink_message__get_packed_size
                     (const Router__UplinkMessage *message)
{
  assert(message->base.descriptor == &router__uplink_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__uplink_message__pack
                     (const Router__UplinkMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__uplink_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__uplink_message__pack_to_buffer
                     (const Router__UplinkMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__uplink_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__UplinkMessage *
       router__uplink_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__UplinkMessage *)
     protobuf_c_message_unpack (&router__uplink_message__descriptor,
                                allocator, len, data);
}
void   router__uplink_message__free_unpacked
                     (Router__UplinkMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__uplink_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__downlink_message__init
                     (Router__DownlinkMessage         *message)
{
  static Router__DownlinkMessage init_value = ROUTER__DOWNLINK_MESSAGE__INIT;
  *message = init_value;
}
size_t router__downlink_message__get_packed_size
                     (const Router__DownlinkMessage *message)
{
  assert(message->base.descriptor == &router__downlink_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__downlink_message__pack
                     (const Router__DownlinkMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__downlink_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__downlink_message__pack_to_buffer
                     (const Router__DownlinkMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__downlink_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__DownlinkMessage *
       router__downlink_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__DownlinkMessage *)
     protobuf_c_message_unpack (&router__downlink_message__descriptor,
                                allocator, len, data);
}
void   router__downlink_message__free_unpacked
                     (Router__DownlinkMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__downlink_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__device_activation_request__init
                     (Router__DeviceActivationRequest         *message)
{
  static Router__DeviceActivationRequest init_value = ROUTER__DEVICE_ACTIVATION_REQUEST__INIT;
  *message = init_value;
}
size_t router__device_activation_request__get_packed_size
                     (const Router__DeviceActivationRequest *message)
{
  assert(message->base.descriptor == &router__device_activation_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__device_activation_request__pack
                     (const Router__DeviceActivationRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__device_activation_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__device_activation_request__pack_to_buffer
                     (const Router__DeviceActivationRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__device_activation_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__DeviceActivationRequest *
       router__device_activation_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__DeviceActivationRequest *)
     protobuf_c_message_unpack (&router__device_activation_request__descriptor,
                                allocator, len, data);
}
void   router__device_activation_request__free_unpacked
                     (Router__DeviceActivationRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__device_activation_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__device_activation_response__init
                     (Router__DeviceActivationResponse         *message)
{
  static Router__DeviceActivationResponse init_value = ROUTER__DEVICE_ACTIVATION_RESPONSE__INIT;
  *message = init_value;
}
size_t router__device_activation_response__get_packed_size
                     (const Router__DeviceActivationResponse *message)
{
  assert(message->base.descriptor == &router__device_activation_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__device_activation_response__pack
                     (const Router__DeviceActivationResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__device_activation_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__device_activation_response__pack_to_buffer
                     (const Router__DeviceActivationResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__device_activation_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__DeviceActivationResponse *
       router__device_activation_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__DeviceActivationResponse *)
     protobuf_c_message_unpack (&router__device_activation_response__descriptor,
                                allocator, len, data);
}
void   router__device_activation_response__free_unpacked
                     (Router__DeviceActivationResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__device_activation_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__gateway_status_request__init
                     (Router__GatewayStatusRequest         *message)
{
  static Router__GatewayStatusRequest init_value = ROUTER__GATEWAY_STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t router__gateway_status_request__get_packed_size
                     (const Router__GatewayStatusRequest *message)
{
  assert(message->base.descriptor == &router__gateway_status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__gateway_status_request__pack
                     (const Router__GatewayStatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__gateway_status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__gateway_status_request__pack_to_buffer
                     (const Router__GatewayStatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__gateway_status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__GatewayStatusRequest *
       router__gateway_status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__GatewayStatusRequest *)
     protobuf_c_message_unpack (&router__gateway_status_request__descriptor,
                                allocator, len, data);
}
void   router__gateway_status_request__free_unpacked
                     (Router__GatewayStatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__gateway_status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__gateway_status_response__init
                     (Router__GatewayStatusResponse         *message)
{
  static Router__GatewayStatusResponse init_value = ROUTER__GATEWAY_STATUS_RESPONSE__INIT;
  *message = init_value;
}
size_t router__gateway_status_response__get_packed_size
                     (const Router__GatewayStatusResponse *message)
{
  assert(message->base.descriptor == &router__gateway_status_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__gateway_status_response__pack
                     (const Router__GatewayStatusResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__gateway_status_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__gateway_status_response__pack_to_buffer
                     (const Router__GatewayStatusResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__gateway_status_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__GatewayStatusResponse *
       router__gateway_status_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__GatewayStatusResponse *)
     protobuf_c_message_unpack (&router__gateway_status_response__descriptor,
                                allocator, len, data);
}
void   router__gateway_status_response__free_unpacked
                     (Router__GatewayStatusResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__gateway_status_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__status_request__init
                     (Router__StatusRequest         *message)
{
  static Router__StatusRequest init_value = ROUTER__STATUS_REQUEST__INIT;
  *message = init_value;
}
size_t router__status_request__get_packed_size
                     (const Router__StatusRequest *message)
{
  assert(message->base.descriptor == &router__status_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__status_request__pack
                     (const Router__StatusRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__status_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__status_request__pack_to_buffer
                     (const Router__StatusRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__status_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__StatusRequest *
       router__status_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__StatusRequest *)
     protobuf_c_message_unpack (&router__status_request__descriptor,
                                allocator, len, data);
}
void   router__status_request__free_unpacked
                     (Router__StatusRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__status_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   router__status__init
                     (Router__Status         *message)
{
  static Router__Status init_value = ROUTER__STATUS__INIT;
  *message = init_value;
}
size_t router__status__get_packed_size
                     (const Router__Status *message)
{
  assert(message->base.descriptor == &router__status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t router__status__pack
                     (const Router__Status *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &router__status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t router__status__pack_to_buffer
                     (const Router__Status *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &router__status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Router__Status *
       router__status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Router__Status *)
     protobuf_c_message_unpack (&router__status__descriptor,
                                allocator, len, data);
}
void   router__status__free_unpacked
                     (Router__Status *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &router__status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define router__subscribe_request__field_descriptors NULL
#define router__subscribe_request__field_indices_by_name NULL
#define router__subscribe_request__number_ranges NULL
const ProtobufCMessageDescriptor router__subscribe_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.SubscribeRequest",
  "SubscribeRequest",
  "Router__SubscribeRequest",
  "router",
  sizeof(Router__SubscribeRequest),
  0,
  router__subscribe_request__field_descriptors,
  router__subscribe_request__field_indices_by_name,
  0,  router__subscribe_request__number_ranges,
  (ProtobufCMessageInit) router__subscribe_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__uplink_message__field_descriptors[5] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Router__UplinkMessage, has_payload),
    offsetof(Router__UplinkMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__UplinkMessage, message),
    &protocol__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_metadata",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__UplinkMessage, protocol_metadata),
    &protocol__rx_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_metadata",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__UplinkMessage, gateway_metadata),
    &gateway__rx_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trace",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__UplinkMessage, trace),
    &trace__trace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__uplink_message__field_indices_by_name[] = {
  3,   /* field[3] = gateway_metadata */
  1,   /* field[1] = message */
  0,   /* field[0] = payload */
  2,   /* field[2] = protocol_metadata */
  4,   /* field[4] = trace */
};
static const ProtobufCIntRange router__uplink_message__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 21, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor router__uplink_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.UplinkMessage",
  "UplinkMessage",
  "Router__UplinkMessage",
  "router",
  sizeof(Router__UplinkMessage),
  5,
  router__uplink_message__field_descriptors,
  router__uplink_message__field_indices_by_name,
  3,  router__uplink_message__number_ranges,
  (ProtobufCMessageInit) router__uplink_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__downlink_message__field_descriptors[5] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Router__DownlinkMessage, has_payload),
    offsetof(Router__DownlinkMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DownlinkMessage, message),
    &protocol__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_configuration",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DownlinkMessage, protocol_configuration),
    &protocol__tx_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_configuration",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DownlinkMessage, gateway_configuration),
    &gateway__tx_configuration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trace",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DownlinkMessage, trace),
    &trace__trace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__downlink_message__field_indices_by_name[] = {
  3,   /* field[3] = gateway_configuration */
  1,   /* field[1] = message */
  0,   /* field[0] = payload */
  2,   /* field[2] = protocol_configuration */
  4,   /* field[4] = trace */
};
static const ProtobufCIntRange router__downlink_message__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 21, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor router__downlink_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.DownlinkMessage",
  "DownlinkMessage",
  "Router__DownlinkMessage",
  "router",
  sizeof(Router__DownlinkMessage),
  5,
  router__downlink_message__field_descriptors,
  router__downlink_message__field_indices_by_name,
  3,  router__downlink_message__number_ranges,
  (ProtobufCMessageInit) router__downlink_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__device_activation_request__field_descriptors[8] =
{
  {
    "payload",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Router__DeviceActivationRequest, has_payload),
    offsetof(Router__DeviceActivationRequest, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DeviceActivationRequest, message),
    &protocol__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev_eui",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Router__DeviceActivationRequest, has_dev_eui),
    offsetof(Router__DeviceActivationRequest, dev_eui),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_eui",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Router__DeviceActivationRequest, has_app_eui),
    offsetof(Router__DeviceActivationRequest, app_eui),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol_metadata",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DeviceActivationRequest, protocol_metadata),
    &protocol__rx_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_metadata",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DeviceActivationRequest, gateway_metadata),
    &gateway__rx_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activation_metadata",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DeviceActivationRequest, activation_metadata),
    &protocol__activation_metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trace",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__DeviceActivationRequest, trace),
    &trace__trace__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__device_activation_request__field_indices_by_name[] = {
  6,   /* field[6] = activation_metadata */
  3,   /* field[3] = app_eui */
  2,   /* field[2] = dev_eui */
  5,   /* field[5] = gateway_metadata */
  1,   /* field[1] = message */
  0,   /* field[0] = payload */
  4,   /* field[4] = protocol_metadata */
  7,   /* field[7] = trace */
};
static const ProtobufCIntRange router__device_activation_request__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 21, 4 },
  { 31, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor router__device_activation_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.DeviceActivationRequest",
  "DeviceActivationRequest",
  "Router__DeviceActivationRequest",
  "router",
  sizeof(Router__DeviceActivationRequest),
  8,
  router__device_activation_request__field_descriptors,
  router__device_activation_request__field_indices_by_name,
  4,  router__device_activation_request__number_ranges,
  (ProtobufCMessageInit) router__device_activation_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define router__device_activation_response__field_descriptors NULL
#define router__device_activation_response__field_indices_by_name NULL
#define router__device_activation_response__number_ranges NULL
const ProtobufCMessageDescriptor router__device_activation_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.DeviceActivationResponse",
  "DeviceActivationResponse",
  "Router__DeviceActivationResponse",
  "router",
  sizeof(Router__DeviceActivationResponse),
  0,
  router__device_activation_response__field_descriptors,
  router__device_activation_response__field_indices_by_name,
  0,  router__device_activation_response__number_ranges,
  (ProtobufCMessageInit) router__device_activation_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__gateway_status_request__field_descriptors[1] =
{
  {
    "gateway_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Router__GatewayStatusRequest, gateway_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__gateway_status_request__field_indices_by_name[] = {
  0,   /* field[0] = gateway_id */
};
static const ProtobufCIntRange router__gateway_status_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor router__gateway_status_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.GatewayStatusRequest",
  "GatewayStatusRequest",
  "Router__GatewayStatusRequest",
  "router",
  sizeof(Router__GatewayStatusRequest),
  1,
  router__gateway_status_request__field_descriptors,
  router__gateway_status_request__field_indices_by_name,
  1,  router__gateway_status_request__number_ranges,
  (ProtobufCMessageInit) router__gateway_status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__gateway_status_response__field_descriptors[2] =
{
  {
    "last_seen",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Router__GatewayStatusResponse, has_last_seen),
    offsetof(Router__GatewayStatusResponse, last_seen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__GatewayStatusResponse, status),
    &gateway__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__gateway_status_response__field_indices_by_name[] = {
  0,   /* field[0] = last_seen */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange router__gateway_status_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor router__gateway_status_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.GatewayStatusResponse",
  "GatewayStatusResponse",
  "Router__GatewayStatusResponse",
  "router",
  sizeof(Router__GatewayStatusResponse),
  2,
  router__gateway_status_response__field_descriptors,
  router__gateway_status_response__field_indices_by_name,
  1,  router__gateway_status_response__number_ranges,
  (ProtobufCMessageInit) router__gateway_status_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define router__status_request__field_descriptors NULL
#define router__status_request__field_indices_by_name NULL
#define router__status_request__number_ranges NULL
const ProtobufCMessageDescriptor router__status_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.StatusRequest",
  "StatusRequest",
  "Router__StatusRequest",
  "router",
  sizeof(Router__StatusRequest),
  0,
  router__status_request__field_descriptors,
  router__status_request__field_indices_by_name,
  0,  router__status_request__number_ranges,
  (ProtobufCMessageInit) router__status_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor router__status__field_descriptors[8] =
{
  {
    "system",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, system),
    &api__system_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, component),
    &api__component_stats__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gateway_status",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, gateway_status),
    &api__rates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uplink",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, uplink),
    &api__rates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "downlink",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, downlink),
    &api__rates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activations",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Router__Status, activations),
    &api__rates__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_gateways",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Router__Status, has_connected_gateways),
    offsetof(Router__Status, connected_gateways),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connected_brokers",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Router__Status, has_connected_brokers),
    offsetof(Router__Status, connected_brokers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned router__status__field_indices_by_name[] = {
  5,   /* field[5] = activations */
  1,   /* field[1] = component */
  7,   /* field[7] = connected_brokers */
  6,   /* field[6] = connected_gateways */
  4,   /* field[4] = downlink */
  2,   /* field[2] = gateway_status */
  0,   /* field[0] = system */
  3,   /* field[3] = uplink */
};
static const ProtobufCIntRange router__status__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 11, 2 },
  { 21, 6 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor router__status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "router.Status",
  "Status",
  "Router__Status",
  "router",
  sizeof(Router__Status),
  8,
  router__status__field_descriptors,
  router__status__field_indices_by_name,
  3,  router__status__number_ranges,
  (ProtobufCMessageInit) router__status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor router__router__method_descriptors[4] =
{
  { "GatewayStatus", &gateway__status__descriptor, &google__protobuf__empty__descriptor },
  { "Uplink", &router__uplink_message__descriptor, &google__protobuf__empty__descriptor },
  { "Subscribe", &router__subscribe_request__descriptor, &router__downlink_message__descriptor },
  { "Activate", &router__device_activation_request__descriptor, &router__device_activation_response__descriptor },
};
const unsigned router__router__method_indices_by_name[] = {
  3,        /* Activate */
  0,        /* GatewayStatus */
  2,        /* Subscribe */
  1         /* Uplink */
};
const ProtobufCServiceDescriptor router__router__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "router.Router",
  "Router",
  "Router__Router",
  "router",
  4,
  router__router__method_descriptors,
  router__router__method_indices_by_name
};
void router__router__gateway_status(ProtobufCService *service,
                                    const Gateway__Status *input,
                                    Google__Protobuf__Empty_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &router__router__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router__uplink(ProtobufCService *service,
                            const Router__UplinkMessage *input,
                            Google__Protobuf__Empty_Closure closure,
                            void *closure_data)
{
  assert(service->descriptor == &router__router__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router__subscribe(ProtobufCService *service,
                               const Router__SubscribeRequest *input,
                               Router__DownlinkMessage_Closure closure,
                               void *closure_data)
{
  assert(service->descriptor == &router__router__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router__activate(ProtobufCService *service,
                              const Router__DeviceActivationRequest *input,
                              Router__DeviceActivationResponse_Closure closure,
                              void *closure_data)
{
  assert(service->descriptor == &router__router__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router__init (Router__Router_Service *service,
                           Router__Router_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &router__router__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
static const ProtobufCMethodDescriptor router__router_manager__method_descriptors[2] =
{
  { "GatewayStatus", &router__gateway_status_request__descriptor, &router__gateway_status_response__descriptor },
  { "GetStatus", &router__status_request__descriptor, &router__status__descriptor },
};
const unsigned router__router_manager__method_indices_by_name[] = {
  0,        /* GatewayStatus */
  1         /* GetStatus */
};
const ProtobufCServiceDescriptor router__router_manager__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "router.RouterManager",
  "RouterManager",
  "Router__RouterManager",
  "router",
  2,
  router__router_manager__method_descriptors,
  router__router_manager__method_indices_by_name
};
void router__router_manager__gateway_status(ProtobufCService *service,
                                            const Router__GatewayStatusRequest *input,
                                            Router__GatewayStatusResponse_Closure closure,
                                            void *closure_data)
{
  assert(service->descriptor == &router__router_manager__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router_manager__get_status(ProtobufCService *service,
                                        const Router__StatusRequest *input,
                                        Router__Status_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &router__router_manager__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void router__router_manager__init (Router__RouterManager_Service *service,
                                   Router__RouterManager_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &router__router_manager__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
