/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/TheThingsNetwork/ttn/api/trace/trace.proto */

#ifndef PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2ftrace_2ftrace_2eproto__INCLUDED
#define PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2ftrace_2ftrace_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Trace__Trace Trace__Trace;
typedef struct _Trace__Trace__MetadataEntry Trace__Trace__MetadataEntry;


/* --- enums --- */


/* --- messages --- */

struct  _Trace__Trace__MetadataEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define TRACE__TRACE__METADATA_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trace__trace__metadata_entry__descriptor) \
    , NULL, NULL }


/*
 * Trace information
 */
struct  _Trace__Trace
{
  ProtobufCMessage base;
  /*
   * Generated ID
   */
  char *id;
  /*
   * Time in Unix nanoseconds
   */
  protobuf_c_boolean has_time;
  int64_t time;
  /*
   * The ID of the component
   */
  char *service_id;
  /*
   * The name of the component (router/broker/handler)
   */
  char *service_name;
  /*
   * Short event name
   */
  char *event;
  /*
   * metadata for the event
   */
  size_t n_metadata;
  Trace__Trace__MetadataEntry **metadata;
  /*
   * Parents of the event
   */
  size_t n_parents;
  Trace__Trace **parents;
};
#define TRACE__TRACE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trace__trace__descriptor) \
    , NULL, 0,0, NULL, NULL, NULL, 0,NULL, 0,NULL }


/* Trace__Trace__MetadataEntry methods */
void   trace__trace__metadata_entry__init
                     (Trace__Trace__MetadataEntry         *message);
/* Trace__Trace methods */
void   trace__trace__init
                     (Trace__Trace         *message);
size_t trace__trace__get_packed_size
                     (const Trace__Trace   *message);
size_t trace__trace__pack
                     (const Trace__Trace   *message,
                      uint8_t             *out);
size_t trace__trace__pack_to_buffer
                     (const Trace__Trace   *message,
                      ProtobufCBuffer     *buffer);
Trace__Trace *
       trace__trace__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trace__trace__free_unpacked
                     (Trace__Trace *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Trace__Trace__MetadataEntry_Closure)
                 (const Trace__Trace__MetadataEntry *message,
                  void *closure_data);
typedef void (*Trace__Trace_Closure)
                 (const Trace__Trace *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor trace__trace__descriptor;
extern const ProtobufCMessageDescriptor trace__trace__metadata_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2ftrace_2ftrace_2eproto__INCLUDED */
