/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/TheThingsNetwork/ttn/api/protocol/lorawan/lorawan.proto */

#ifndef PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2fprotocol_2florawan_2florawan_2eproto__INCLUDED
#define PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2fprotocol_2florawan_2florawan_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "github.com/gogo/protobuf/gogoproto/gogo.pb-c.h"

typedef struct _Lorawan__Metadata Lorawan__Metadata;
typedef struct _Lorawan__TxConfiguration Lorawan__TxConfiguration;
typedef struct _Lorawan__ActivationMetadata Lorawan__ActivationMetadata;


/* --- enums --- */

typedef enum _Lorawan__Modulation {
  LORAWAN__MODULATION__LORA = 0,
  LORAWAN__MODULATION__FSK = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORAWAN__MODULATION)
} Lorawan__Modulation;
typedef enum _Lorawan__Region {
  LORAWAN__REGION__EU_863_870 = 0,
  LORAWAN__REGION__US_902_928 = 1,
  LORAWAN__REGION__CN_779_787 = 2,
  LORAWAN__REGION__EU_433 = 3,
  LORAWAN__REGION__AU_915_928 = 4,
  LORAWAN__REGION__CN_470_510 = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LORAWAN__REGION)
} Lorawan__Region;

/* --- messages --- */

struct  _Lorawan__Metadata
{
  ProtobufCMessage base;
  protobuf_c_boolean has_modulation;
  Lorawan__Modulation modulation;
  /*
   * LoRa data rate - SF{spreadingfactor}BW{bandwidth}
   */
  char *data_rate;
  /*
   * FSK bit rate in bit/s
   */
  protobuf_c_boolean has_bit_rate;
  uint32_t bit_rate;
  /*
   * LoRa coding rate
   */
  char *coding_rate;
  /*
   * Store the full 32 bit FCnt
   */
  protobuf_c_boolean has_f_cnt;
  uint32_t f_cnt;
};
#define LORAWAN__METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lorawan__metadata__descriptor) \
    , 0,0, NULL, 0,0, NULL, 0,0 }


struct  _Lorawan__TxConfiguration
{
  ProtobufCMessage base;
  protobuf_c_boolean has_modulation;
  Lorawan__Modulation modulation;
  /*
   * LoRa data rate - SF{spreadingfactor}BW{bandwidth}
   */
  char *data_rate;
  /*
   * FSK bit rate in bit/s
   */
  protobuf_c_boolean has_bit_rate;
  uint32_t bit_rate;
  /*
   * LoRa coding rate
   */
  char *coding_rate;
  /*
   * Store the full 32 bit FCnt
   */
  protobuf_c_boolean has_f_cnt;
  uint32_t f_cnt;
};
#define LORAWAN__TX_CONFIGURATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lorawan__tx_configuration__descriptor) \
    , 0,0, NULL, 0,0, NULL, 0,0 }


struct  _Lorawan__ActivationMetadata
{
  ProtobufCMessage base;
  protobuf_c_boolean has_app_eui;
  ProtobufCBinaryData app_eui;
  protobuf_c_boolean has_dev_eui;
  ProtobufCBinaryData dev_eui;
  protobuf_c_boolean has_dev_addr;
  ProtobufCBinaryData dev_addr;
  protobuf_c_boolean has_nwk_s_key;
  ProtobufCBinaryData nwk_s_key;
  protobuf_c_boolean has_rx1_dr_offset;
  uint32_t rx1_dr_offset;
  protobuf_c_boolean has_rx2_dr;
  uint32_t rx2_dr;
  protobuf_c_boolean has_rx_delay;
  uint32_t rx_delay;
  size_t n_cf_list;
  uint64_t *cf_list;
};
#define LORAWAN__ACTIVATION_METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&lorawan__activation_metadata__descriptor) \
    , 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,0, 0,NULL }


/* Lorawan__Metadata methods */
void   lorawan__metadata__init
                     (Lorawan__Metadata         *message);
size_t lorawan__metadata__get_packed_size
                     (const Lorawan__Metadata   *message);
size_t lorawan__metadata__pack
                     (const Lorawan__Metadata   *message,
                      uint8_t             *out);
size_t lorawan__metadata__pack_to_buffer
                     (const Lorawan__Metadata   *message,
                      ProtobufCBuffer     *buffer);
Lorawan__Metadata *
       lorawan__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lorawan__metadata__free_unpacked
                     (Lorawan__Metadata *message,
                      ProtobufCAllocator *allocator);
/* Lorawan__TxConfiguration methods */
void   lorawan__tx_configuration__init
                     (Lorawan__TxConfiguration         *message);
size_t lorawan__tx_configuration__get_packed_size
                     (const Lorawan__TxConfiguration   *message);
size_t lorawan__tx_configuration__pack
                     (const Lorawan__TxConfiguration   *message,
                      uint8_t             *out);
size_t lorawan__tx_configuration__pack_to_buffer
                     (const Lorawan__TxConfiguration   *message,
                      ProtobufCBuffer     *buffer);
Lorawan__TxConfiguration *
       lorawan__tx_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lorawan__tx_configuration__free_unpacked
                     (Lorawan__TxConfiguration *message,
                      ProtobufCAllocator *allocator);
/* Lorawan__ActivationMetadata methods */
void   lorawan__activation_metadata__init
                     (Lorawan__ActivationMetadata         *message);
size_t lorawan__activation_metadata__get_packed_size
                     (const Lorawan__ActivationMetadata   *message);
size_t lorawan__activation_metadata__pack
                     (const Lorawan__ActivationMetadata   *message,
                      uint8_t             *out);
size_t lorawan__activation_metadata__pack_to_buffer
                     (const Lorawan__ActivationMetadata   *message,
                      ProtobufCBuffer     *buffer);
Lorawan__ActivationMetadata *
       lorawan__activation_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   lorawan__activation_metadata__free_unpacked
                     (Lorawan__ActivationMetadata *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Lorawan__Metadata_Closure)
                 (const Lorawan__Metadata *message,
                  void *closure_data);
typedef void (*Lorawan__TxConfiguration_Closure)
                 (const Lorawan__TxConfiguration *message,
                  void *closure_data);
typedef void (*Lorawan__ActivationMetadata_Closure)
                 (const Lorawan__ActivationMetadata *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    lorawan__modulation__descriptor;
extern const ProtobufCEnumDescriptor    lorawan__region__descriptor;
extern const ProtobufCMessageDescriptor lorawan__metadata__descriptor;
extern const ProtobufCMessageDescriptor lorawan__tx_configuration__descriptor;
extern const ProtobufCMessageDescriptor lorawan__activation_metadata__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_github_2ecom_2fTheThingsNetwork_2fttn_2fapi_2fprotocol_2florawan_2florawan_2eproto__INCLUDED */
