/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: github.com/TheThingsNetwork/ttn/api/protocol/lorawan/lorawan.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "github.com/TheThingsNetwork/ttn/api/protocol/lorawan/lorawan.pb-c.h"
void   lorawan__metadata__init
                     (Lorawan__Metadata         *message)
{
  static Lorawan__Metadata init_value = LORAWAN__METADATA__INIT;
  *message = init_value;
}
size_t lorawan__metadata__get_packed_size
                     (const Lorawan__Metadata *message)
{
  assert(message->base.descriptor == &lorawan__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lorawan__metadata__pack
                     (const Lorawan__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lorawan__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lorawan__metadata__pack_to_buffer
                     (const Lorawan__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lorawan__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lorawan__Metadata *
       lorawan__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lorawan__Metadata *)
     protobuf_c_message_unpack (&lorawan__metadata__descriptor,
                                allocator, len, data);
}
void   lorawan__metadata__free_unpacked
                     (Lorawan__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &lorawan__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lorawan__tx_configuration__init
                     (Lorawan__TxConfiguration         *message)
{
  static Lorawan__TxConfiguration init_value = LORAWAN__TX_CONFIGURATION__INIT;
  *message = init_value;
}
size_t lorawan__tx_configuration__get_packed_size
                     (const Lorawan__TxConfiguration *message)
{
  assert(message->base.descriptor == &lorawan__tx_configuration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lorawan__tx_configuration__pack
                     (const Lorawan__TxConfiguration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lorawan__tx_configuration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lorawan__tx_configuration__pack_to_buffer
                     (const Lorawan__TxConfiguration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lorawan__tx_configuration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lorawan__TxConfiguration *
       lorawan__tx_configuration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lorawan__TxConfiguration *)
     protobuf_c_message_unpack (&lorawan__tx_configuration__descriptor,
                                allocator, len, data);
}
void   lorawan__tx_configuration__free_unpacked
                     (Lorawan__TxConfiguration *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &lorawan__tx_configuration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lorawan__activation_metadata__init
                     (Lorawan__ActivationMetadata         *message)
{
  static Lorawan__ActivationMetadata init_value = LORAWAN__ACTIVATION_METADATA__INIT;
  *message = init_value;
}
size_t lorawan__activation_metadata__get_packed_size
                     (const Lorawan__ActivationMetadata *message)
{
  assert(message->base.descriptor == &lorawan__activation_metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lorawan__activation_metadata__pack
                     (const Lorawan__ActivationMetadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lorawan__activation_metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lorawan__activation_metadata__pack_to_buffer
                     (const Lorawan__ActivationMetadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lorawan__activation_metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Lorawan__ActivationMetadata *
       lorawan__activation_metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Lorawan__ActivationMetadata *)
     protobuf_c_message_unpack (&lorawan__activation_metadata__descriptor,
                                allocator, len, data);
}
void   lorawan__activation_metadata__free_unpacked
                     (Lorawan__ActivationMetadata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &lorawan__activation_metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lorawan__metadata__field_descriptors[5] =
{
  {
    "modulation",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Lorawan__Metadata, has_modulation),
    offsetof(Lorawan__Metadata, modulation),
    &lorawan__modulation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_rate",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lorawan__Metadata, data_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bit_rate",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__Metadata, has_bit_rate),
    offsetof(Lorawan__Metadata, bit_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coding_rate",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lorawan__Metadata, coding_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f_cnt",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__Metadata, has_f_cnt),
    offsetof(Lorawan__Metadata, f_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lorawan__metadata__field_indices_by_name[] = {
  2,   /* field[2] = bit_rate */
  3,   /* field[3] = coding_rate */
  1,   /* field[1] = data_rate */
  4,   /* field[4] = f_cnt */
  0,   /* field[0] = modulation */
};
static const ProtobufCIntRange lorawan__metadata__number_ranges[1 + 1] =
{
  { 11, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor lorawan__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lorawan.Metadata",
  "Metadata",
  "Lorawan__Metadata",
  "lorawan",
  sizeof(Lorawan__Metadata),
  5,
  lorawan__metadata__field_descriptors,
  lorawan__metadata__field_indices_by_name,
  1,  lorawan__metadata__number_ranges,
  (ProtobufCMessageInit) lorawan__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lorawan__tx_configuration__field_descriptors[5] =
{
  {
    "modulation",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Lorawan__TxConfiguration, has_modulation),
    offsetof(Lorawan__TxConfiguration, modulation),
    &lorawan__modulation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_rate",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lorawan__TxConfiguration, data_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bit_rate",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__TxConfiguration, has_bit_rate),
    offsetof(Lorawan__TxConfiguration, bit_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coding_rate",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Lorawan__TxConfiguration, coding_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f_cnt",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__TxConfiguration, has_f_cnt),
    offsetof(Lorawan__TxConfiguration, f_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lorawan__tx_configuration__field_indices_by_name[] = {
  2,   /* field[2] = bit_rate */
  3,   /* field[3] = coding_rate */
  1,   /* field[1] = data_rate */
  4,   /* field[4] = f_cnt */
  0,   /* field[0] = modulation */
};
static const ProtobufCIntRange lorawan__tx_configuration__number_ranges[1 + 1] =
{
  { 11, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor lorawan__tx_configuration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lorawan.TxConfiguration",
  "TxConfiguration",
  "Lorawan__TxConfiguration",
  "lorawan",
  sizeof(Lorawan__TxConfiguration),
  5,
  lorawan__tx_configuration__field_descriptors,
  lorawan__tx_configuration__field_indices_by_name,
  1,  lorawan__tx_configuration__number_ranges,
  (ProtobufCMessageInit) lorawan__tx_configuration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lorawan__activation_metadata__field_descriptors[8] =
{
  {
    "app_eui",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Lorawan__ActivationMetadata, has_app_eui),
    offsetof(Lorawan__ActivationMetadata, app_eui),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev_eui",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Lorawan__ActivationMetadata, has_dev_eui),
    offsetof(Lorawan__ActivationMetadata, dev_eui),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev_addr",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Lorawan__ActivationMetadata, has_dev_addr),
    offsetof(Lorawan__ActivationMetadata, dev_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nwk_s_key",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Lorawan__ActivationMetadata, has_nwk_s_key),
    offsetof(Lorawan__ActivationMetadata, nwk_s_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx1_dr_offset",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__ActivationMetadata, has_rx1_dr_offset),
    offsetof(Lorawan__ActivationMetadata, rx1_dr_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx2_dr",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__ActivationMetadata, has_rx2_dr),
    offsetof(Lorawan__ActivationMetadata, rx2_dr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rx_delay",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Lorawan__ActivationMetadata, has_rx_delay),
    offsetof(Lorawan__ActivationMetadata, rx_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cf_list",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Lorawan__ActivationMetadata, n_cf_list),
    offsetof(Lorawan__ActivationMetadata, cf_list),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lorawan__activation_metadata__field_indices_by_name[] = {
  0,   /* field[0] = app_eui */
  7,   /* field[7] = cf_list */
  2,   /* field[2] = dev_addr */
  1,   /* field[1] = dev_eui */
  3,   /* field[3] = nwk_s_key */
  4,   /* field[4] = rx1_dr_offset */
  5,   /* field[5] = rx2_dr */
  6,   /* field[6] = rx_delay */
};
static const ProtobufCIntRange lorawan__activation_metadata__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 11, 4 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor lorawan__activation_metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lorawan.ActivationMetadata",
  "ActivationMetadata",
  "Lorawan__ActivationMetadata",
  "lorawan",
  sizeof(Lorawan__ActivationMetadata),
  8,
  lorawan__activation_metadata__field_descriptors,
  lorawan__activation_metadata__field_indices_by_name,
  2,  lorawan__activation_metadata__number_ranges,
  (ProtobufCMessageInit) lorawan__activation_metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue lorawan__modulation__enum_values_by_number[2] =
{
  { "LORA", "LORAWAN__MODULATION__LORA", 0 },
  { "FSK", "LORAWAN__MODULATION__FSK", 1 },
};
static const ProtobufCIntRange lorawan__modulation__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex lorawan__modulation__enum_values_by_name[2] =
{
  { "FSK", 1 },
  { "LORA", 0 },
};
const ProtobufCEnumDescriptor lorawan__modulation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lorawan.Modulation",
  "Modulation",
  "Lorawan__Modulation",
  "lorawan",
  2,
  lorawan__modulation__enum_values_by_number,
  2,
  lorawan__modulation__enum_values_by_name,
  1,
  lorawan__modulation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue lorawan__region__enum_values_by_number[6] =
{
  { "EU_863_870", "LORAWAN__REGION__EU_863_870", 0 },
  { "US_902_928", "LORAWAN__REGION__US_902_928", 1 },
  { "CN_779_787", "LORAWAN__REGION__CN_779_787", 2 },
  { "EU_433", "LORAWAN__REGION__EU_433", 3 },
  { "AU_915_928", "LORAWAN__REGION__AU_915_928", 4 },
  { "CN_470_510", "LORAWAN__REGION__CN_470_510", 5 },
};
static const ProtobufCIntRange lorawan__region__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex lorawan__region__enum_values_by_name[6] =
{
  { "AU_915_928", 4 },
  { "CN_470_510", 5 },
  { "CN_779_787", 2 },
  { "EU_433", 3 },
  { "EU_863_870", 0 },
  { "US_902_928", 1 },
};
const ProtobufCEnumDescriptor lorawan__region__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lorawan.Region",
  "Region",
  "Lorawan__Region",
  "lorawan",
  6,
  lorawan__region__enum_values_by_number,
  6,
  lorawan__region__enum_values_by_name,
  1,
  lorawan__region__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
